name: Detekt All

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin
      - name: detekt
        uses: natiginfo/action-detekt-all@1.21.0-RC1
        with:
          args: -ex MaxLineLength -ex ReturnCount -ex TooGenericExceptionCaught -ex TooManyFunctions
